Network:
  -Name: matcom

OrdererOrgs:
  - Name: Orderer
    Domain: acme.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost

PeerOrgs:
  - Name: Org1
    Domain: org1.acme.com
    Peers:
      - Name: peer0
        Domain: peer0.org1.acme.com

    
  - Name: Org2
    Domain: org2.acme.com
    Peers:
      - Name: peer1
        Domain: peer1.org2.acme.com
  - Name: Org3
    Domain: org3.acme.com
    Peers:
      - Name: peer2
        Domain: peer1.org3.acme.com
