Network:
  -Name: matcom

OrdererOrgs:
  - Name: Orderer
    Domain: matcom.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost

PeerOrgs:
  - Name: Org1
    Domain: org1.matcom.com
    Peers:
      - Name: peer0
        Domain: peer0.org1.matcom.com

    
  - Name: Org2
    Domain: org2.matcom.com
    Peers:
      - Name: peer1
        Domain: peer0.org2.matcom.com
  - Name: Org3
    Domain: org3.matcom.com
    Peers:
      - Name: peer2
        Domain: peer0.org3.matcom.com
